spring.application.name=be
server.port=8083


# Hibernate Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/english_app
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.jwt.secret=75b6eef0a66010157b5a3aa33c908c414f4c8a0e5e4e700810b8c99acbe40195897033d7e012cc96b98d51476916c41daeb12b0e46064d947d8179d2feec1cbb28643c6a864be4d7ac0b962060a9810ee3ac3be7331ebec8106a473cc4c04d13af05f52fb97fee5506aab229b8ecfe76c41f4db383929623eb0242d67fb8e2a6be0b96cd900e0f552858f0a019a58c5992fcc39d9cb01ccb07e8c632ee6269a7f22b6814ebe82e9b60e02ec71aa7ea0e871f17a59e08da105d7ca01d4b896a13da8fcfb58498e11cd79ec2b12c71dfc53eb4b56897fe28e6cb2f87fc6e38cae896186bd5227923ebeac0a3a0082c445082cc3cad3021989f5d15f4aed0ebe6a0
app.jwt.expiration=86400000




spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=21130558@st.hcmuaf.edu.vn
spring.mail.password=cwxi fynd ianh lxne
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.cloud-storage.api-key=793588286116743
app.cloud-storage.api-secret=JT9hqjA7_-GCcuR53yUM5TXQ43k
app.cloud-storage.cloud-name=dpnvdbzyo
app.cloud-storage.asset-folder=english_app
# ??t gi?i h?n cho file upload (ví d?: 50MB)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# Thông tin c?u hình VNPay
vnpay.tmnCode=ZDJRTS3T
vnpay.hashSecret=MWQM3FP41I6HOM2W00T9sYI4707TCZ9OC
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8083/payment-return